# Copyright 2009 The Go Authors. All rights reserved.
# Copyright 2014-2015 The Gogs Authors. All rights reserved.
# Copyright 2015 The Gitea Authors. All rights reserved.
# Use of this source code is governed by a BSD-style
# license that can be found in the LICENSE file.

include $(GOROOT)/src/Make.inc

TARG=github.com/mmitton/asn1-ber
GOFILES=\
	ber.go\

include $(GOROOT)/src/Make.pkg
